---

- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Apt hold packages versions
  command: "apt-mark hold {{ item }}"
  loop: "{{ hold_packages }}"
  args:
    warn: false

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Remove unused dependencies (no longer required)
  apt:
    autoremove: yes
  when:
    - remove_unused_dependencies

- name: Clean useless packages from the cache
  apt:
    autoclean: yes
  when:
    - remove_unused_dependencies

- name: Apt unhold packages versions
  command: "apt-mark unhold {{ item }}"
  loop: "{{ hold_packages }}"
  args:
    warn: false

- name: Check if a reboot is needed
  command: cat /var/run/reboot-required.pkgs
  register: reboot_required
  ignore_errors: true

- debug:
    msg: System {{ inventory_hostname }} need REBOOT !
  when: reboot_required.stdout | length > 0
